"""
Phase 3 - Run the business questions and publish the answers  (Week 8)
======================================================================

Executes every query in sql/business_questions.sql against
data/processed/underemployment.db and writes the results to
output/sql_results.md as markdown tables.

WHY WRITE THE RESULTS TO A FILE
-------------------------------
The Week 8 deliverable is "3 answered business questions", not "3 queries".
A reviewer should be able to read the answers without installing anything or
rebuilding a database - while still being able to re-run everything and get
the same numbers. Committing the generated markdown alongside the .sql is what
makes both true at once.

The queries are split on their `-- @question:` marker lines, so the .sql file
stays a plain, runnable script that also works in any SQL client.

Usage
-----
    python scripts/run_sql.py
    python scripts/run_sql.py --print     # to stdout as well
"""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = PROJECT_ROOT / "data" / "processed" / "underemployment.db"
SQL_PATH = PROJECT_ROOT / "sql" / "business_questions.sql"
OUTPUT_PATH = PROJECT_ROOT / "output" / "sql_results.md"

QUESTION_MARKER = re.compile(r"^--\s*@question:\s*(.+)$", re.MULTILINE)


def parse_queries(sql_text: str) -> list[tuple[str, str, str]]:
    """Split the script into (question, commentary, statement) triples."""
    markers = list(QUESTION_MARKER.finditer(sql_text))
    if not markers:
        raise SystemExit(f"No '-- @question:' markers found in {SQL_PATH.name}.")

    blocks: list[tuple[str, str, str]] = []
    for position, marker in enumerate(markers):
        start = marker.end()
        end = markers[position + 1].start() if position + 1 < len(markers) else len(sql_text)
        body = sql_text[start:end].strip()

        # The leading comment lines are the plain-language explanation; the rest
        # is the statement itself.
        commentary, statement = [], []
        for line in body.splitlines():
            if not statement and line.strip().startswith("--"):
                commentary.append(line.strip().lstrip("-").strip())
            elif line.strip():
                statement.append(line)
        blocks.append((marker.group(1).strip(),
                       " ".join(commentary),
                       "\n".join(statement).strip()))
    return blocks


def as_markdown_table(columns: list[str], rows: list[tuple]) -> str:
    if not rows:
        return "_No rows returned._"

    def cell(value) -> str:
        return "—" if value is None else str(value)

    body = [[cell(value) for value in row] for row in rows]
    widths = [max(len(columns[i]), *(len(r[i]) for r in body))
              for i in range(len(columns))]

    lines = ["| " + " | ".join(columns[i].ljust(widths[i])
                               for i in range(len(columns))) + " |",
             "| " + " | ".join("-" * widths[i] for i in range(len(columns))) + " |"]
    lines += ["| " + " | ".join(row[i].ljust(widths[i])
                                for i in range(len(columns))) + " |" for row in body]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run sql/business_questions.sql.")
    parser.add_argument("--print", dest="echo", action="store_true",
                        help="also print the results to stdout")
    args = parser.parse_args(argv)

    if not DB_PATH.exists():
        raise SystemExit(
            f"No database at {DB_PATH.name}. Run:\n"
            f"    python scripts/transform.py\n"
            f"    python scripts/load_db.py"
        )

    blocks = parse_queries(SQL_PATH.read_text(encoding="utf-8"))
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    sections = [
        "# Business Questions — Answered",
        "",
        "Generated by `python scripts/run_sql.py` from "
        "[`sql/business_questions.sql`](../sql/business_questions.sql), run against "
        "`data/processed/underemployment.db`.",
        "",
        "Rebuild everything with:",
        "",
        "```bash",
        "python scripts/transform.py && python scripts/load_db.py && python scripts/run_sql.py",
        "```",
        "",
    ]

    with sqlite3.connect(DB_PATH) as connection:
        connection.execute("PRAGMA foreign_keys = ON")
        for number, (question, commentary, statement) in enumerate(blocks, start=1):
            cursor = connection.execute(statement)
            columns = [description[0] for description in cursor.description]
            rows = cursor.fetchall()

            sections += [
                f"## {number}. {question}",
                "",
                commentary,
                "",
                as_markdown_table(columns, rows),
                "",
                "<details><summary>SQL</summary>",
                "",
                "```sql",
                statement,
                "```",
                "",
                "</details>",
                "",
            ]
            if args.echo:
                print(f"\n{number}. {question}\n")
                print(as_markdown_table(columns, rows))

    OUTPUT_PATH.write_text("\n".join(sections), encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)} "
          f"({len(blocks)} questions answered)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
